"""add_tenant_company_to_invoice_item

Revision ID: 0a8c3bfeb191
Revises: bc221d501185
Create Date: 2026-08-11 20:22:37.064995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8c3bfeb191'
down_revision: Union[str, None] = 'bc221d501185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_item', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('invoice_item', sa.Column('company_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_invoice_item_company_id'), 'invoice_item', ['company_id'], unique=False)
    op.create_index(op.f('ix_invoice_item_tenant_id'), 'invoice_item', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'invoice_item', 'company', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invoice_item', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_item', type_='foreignkey')
    op.drop_constraint(None, 'invoice_item', type_='foreignkey')
    op.drop_index(op.f('ix_invoice_item_tenant_id'), table_name='invoice_item')
    op.drop_index(op.f('ix_invoice_item_company_id'), table_name='invoice_item')
    op.drop_column('invoice_item', 'company_id')
    op.drop_column('invoice_item', 'tenant_id')
    # ### end Alembic commands ###
