"""add fiscal engine config to tenant

Revision ID: add_fiscal_engine_config
Revises: 
Create Date: 2026-08-15 22:50:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_fiscal_engine_config'
down_revision = '0a8c3bfeb191'  # Última migración conocida
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('tenant', sa.Column('fiscal_engine_id', sa.String(length=50), nullable=False, server_default='dgi_uruguay'))
    op.add_column('tenant', sa.Column('fiscal_config', sa.JSON(), nullable=True, server_default='{}'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column('tenant', 'fiscal_config')
    op.drop_column('tenant', 'fiscal_engine_id')
    # ### end Alembic commands ###